"use client";

import { Button } from "@/components/ui/button";
import { DownloadIcon } from "lucide-react";

type Props = {
  fileName: string;
  title: string;
  summary: string;
  createdAt: Date;
};

export function DownloadSummary({
  fileName,
  title,
  summary,
  createdAt,
}: Props) {
  const handleDownload = () => {
    const summaryContent = `# ${title}

    Generated Summary
    Generated On: ${new Date(createdAt).toLocaleDateString()}
    
    ${summary}

    Original File: ${fileName}
    Generated by Sarransh AI
    `;

    // create a blob from the summary content
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    // replace all non-alphanumeric characters with a dash
    a.download = `Summary-${title.replace(/[^a-z0-9]/gi, "-")}.txt`;
    a.click();

    // remove the element from the DOM
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Button onClick={handleDownload} variant="ghost">
      <DownloadIcon />
      Download Summary
    </Button>
  );
}
